@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 - 2021 Free Software Foundation, Inc.
@c See the file g-golf.texi for copying conditions.


@node Structure and Naming Conventions
@subsection Structure and Naming Conventions

G-Golf Core Reference modules and documentation structure and naming
conventions are based, whenever it is possible, on the structure and
naming conventions of the corresponding GNOME library.

To illustrate, let's look at a few GLib, GObject and GObject
Introspection sections and corresponding G-Golf sections and modules
naming examples:

@indentedblock
@strong{Glib}

@table @code

@item @uref{@value{UGLIB-Mem-Alloc}, Memory Allocation}
@ref{Memory Allocation} @*
@code{(g-golf glib mem-alloc)}

@item @uref{@value{UGLIB-Main-Event-Loop}, The Main Event Loop}
@ref{The Main Event Loop} @*
@code{(g-golf glib main-event-loop)}

@item @dots{}

@end table
@end indentedblock


@indentedblock
@strong{GObject}

@table @code

@item @uref{@value{UGOBJECT-Type-Info}, Type Information}
@ref{Type Information} @*
@code{(g-golf gobject type-info)}

@item @uref{@value{UGOBJECT-GObject}, GObject}
@ref{GObject_} @*
@code{(g-golf gobject gobject)}

@item @uref{@value{UGOBJECT-Enum-Flags}, Enumeration and Flag Types}
@ref{Enumeration and Flag Types} @*
@code{(g-golf gobject enum-flags)}

@item @dots{}

@end table
@end indentedblock


@indentedblock
@strong{GObject Introspection}

@table @code

@item @uref{@value{UGIRepository}, GIRepository}
@ref{Repository} @*
@code{(g-golf gi repository)}

@item @uref{@value{UGIcommontypes}, common types}
@ref{Common Types} @*
@code{(g-golf gi common-types)}

@item @uref{@value{UGIBaseInfo}, GIBaseInfo}
@ref{Base Info} @*
@code{(g-golf gi base-info)}

@item @dots{}

@end table
@end indentedblock


Support to the G-Golf Core Reference modules themselves, or additional
functionality to G-Golf as a all, is organized and located in other
(none GNOME library based) modules, such as @code{(g-golf support @dots{})},
@code{g-golf override @dots{})} @dots{}
