@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 - 2020 Free Software Foundation, Inc.
@c See the file g-golf.texi for copying conditions.


@node Project and Documentation Structure
@subsection Project and Documentation Structure

The project and documentation both structure and naming is, whenever it
is possible, based on the @samp{original} documentation structure and
naming of the corresponding library. So far, these are the @code{glib}
(GLib), @code{gobject} (GObject), @code{gdk} (Gdk) and @code{gi}
(GObject Introspection) directories. To illustrate, here are just a few
examples:


@indentedblock
@strong{Glib}

@table @code

@item @uref{@value{UGLIB-Mem-Alloc}, Memory Allocation}
@ref{Memory Allocation} @*
@code{(g-golf glib mem-alloc)}

@item @uref{@value{UGLIB-Main-Event-Loop}, The Main Event Loop}
@ref{The Main Event Loop} @*
@code{(g-golf glib main-event-loop)}

@item @dots{}

@end table
@end indentedblock


@indentedblock
@strong{GObject}

@table @code

@item @uref{@value{UGOBJECT-Type-Info}, Type Information}
@ref{Type Information} @*
@code{(g-golf gobject type-info)}

@item @uref{@value{UGOBJECT-GObject}, GObject}
@ref{GObject_} @*
@code{(g-golf gobject gobject)}

@item @uref{@value{UGOBJECT-Enum-Flags}, Enumeration and Flag Types}
@ref{Enumeration and Flag Types} @*
@code{(g-golf gobject enum-flags)}

@item @dots{}

@end table
@end indentedblock


@indentedblock
@strong{Gdk}

@table @code

@item @uref{@value{UGDK-Events}, Events}
@ref{Events} @*
@code{(g-golf gdk events)}

@item @uref{@value{UGDK-KeyValues}, Key Values}
@ref{Key Values} @*
@code{(g-golf gdk key-values)}

@item @dots{}

@end table
@end indentedblock


@indentedblock
@strong{GObject Introspection}

@table @code

@item @uref{@value{UGIRepository}, GIRepository}
@ref{Repository} @*
@code{(g-golf gi repository)}

@item @uref{@value{UGIcommontypes}, common types}
@ref{Common Types} @*
@code{(g-golf gi common-types)}

@item @uref{@value{UGIBaseInfo}, GIBaseInfo}
@ref{Base Info} @*
@code{(g-golf gi base-info)}

@item @dots{}

@end table
@end indentedblock


Exceptions to the above are the G-Golf modules that provide support to
the core project itself or additional functionality, so far organized in
their respective @code{support}, @code{override} and @code{hl-api}
directory.
