@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 - 2019 Free Software Foundation, Inc.
@c See the file g-golf.texi for copying conditions.


G-Golf uses a series of support modules, each documented in the following
subsections. You may either import them all, like this
@code{(use-modules (g-golf support))}, or individually, such as
@code{(use-modules (g-golf support modules))}, @code{(use-modules (g-golf
support goops))}, ...


@menu
* Modules::
* Goops::
* G-export::
* Enum::
* Flag::
* Struct::
* Union::
* Utilities_::
@end menu


@include cr-support-modules.texi
@include cr-support-goops.texi

@node G-export
@subsection G-export

@include cr-support-enum.texi
@include cr-support-flag.texi
@include cr-support-struct.texi
@include cr-support-union.texi
@include cr-support-utils.texi
